// leave off @2x/@3x
export const images = {
  logo: require("../images/logo_cargolink.png"),
  logoNew: require("../images/CargolinkLogo.png"),
  truck1: require("../images/iconcarma.png"),
  pinbox: require("../images/iconfindwork.png"),
  sheet1: require("../images/iconpostwork.png"),
  word1: require("../images/iconfindtruck.png"),
  truck: require("../images/vehicles/Truck1.png"),
  truck2: require("../images/vehicles/Truck2.png"),
  truck3: require("../images/vehicles/Truck3.png"),
  truck4: require("../images/vehicles/Truck4.png"),
  truck5: require("../images/vehicles/Truck5.png"),
  truck6: require("../images/vehicles/Truck6.png"),
  truck7: require("../images/vehicles/Truck7.png"),
  truck8: require("../images/vehicles/Truck8.png"),
  truck9: require("../images/vehicles/Truck9.png"),
  truck10: require("../images/vehicles/Truck10.png"),
  truck11: require("../images/vehicles/Truck11.png"),
  truck12: require("../images/vehicles/Truck12.png"),
  truck13: require("../images/vehicles/Truck13.png"),
  truck14: require("../images/vehicles/Truck14.png"),
  truck15: require("../images/vehicles/Truck15.png"),
  truck16: require("../images/vehicles/Truck16.png"),
  truck17: require("../images/vehicles/Truck17.png"),
  truck18: require("../images/vehicles/Truck18.png"),
  truck19: require("../images/vehicles/Truck19.png"),
  truck20: require("../images/vehicles/Truck20.png"),
  truck21: require("../images/vehicles/Truck21.png"),
  truck22: require("../images/vehicles/Truck22.png"),
  truck23: require("../images/vehicles/Truck23.png"),
  truck24: require("../images/vehicles/Truck24.png"),
  truck25: require("../images/vehicles/Truck25.png"),
  truck26: require("../images/vehicles/Truck26.png"),
  truck27: require("../images/vehicles/Truck27.png"),
  truck28: require("../images/vehicles/Truck28.png"),
  truck29: require("../images/vehicles/Truck29.png"),
  truck30: require("../images/vehicles/Truck30.png"),
  truck31: require("../images/vehicles/Truck31.png"),
  truck32: require("../images/vehicles/Truck32.png"),
  truck33: require("../images/vehicles/Truck33.png"),
  truck34: require("../images/vehicles/Truck34.png"),
  truck35: require("../images/vehicles/Truck35.png"),
  truck36: require("../images/vehicles/Truck36.png"),
  addTruck1: require("../images/add-truck-icon/S1Truck.png"),
  addTruck2: require("../images/add-truck-icon/S2Truck.png"),
  addTruck2F: require("../images/add-truck-icon/BTruck.png"),
  addTruck2B: require("../images/add-truck-icon/FTruck.png"),
  defaultImage: require("../images/default_image.png"),
  bell: require("../images/bell.png"),
  postJobSuccess: require("../images/post-job-success.png"),
  noImageAvailable: require("../images/no-image-available.jpg"),
  greyMock: require("../images/just_grey_light_grey.jpg"),
  // clearLogo: require('../Images/top_logo.png'),
}

// export default images
