fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

package = load_json(json_path: "./package.json")

desc 'Android: Increment versionCode and set versionName to package.json version.'
private_lane :inc_ver_and do
  increment_version_code(
    gradle_file_path: "./android/app/build.gradle"
  )
  build_number = android_get_version_code(
    gradle_file: "./android/app/build.gradle" # optional
  )

  android_set_version_name(
    gradle_file: "./android/app/build.gradle",
    version_name: version
  )
end


desc 'iOS: Increment build number and set the version to package.json version.'
private_lane :inc_ver_ios do
  increment_build_number(xcodeproj: './ios/CargoLinkMobile.xcodeproj')
  build_number = get_build_number(xcodeproj: "./ios/CargoLinkMobile.xcodeproj")

  increment_version_number(
    xcodeproj: './ios/CargoLinkMobile.xcodeproj',
    version_number: version
  )
  # version = get_version_number(xcodeproj: "./ios/CargoLinkMobile.xcodeproj", target: "CargoLinkMobile")
end


desc 'Bump build numbers, and set the version to match the pacakage.json version.'
lane :bump do
  inc_ver_ios
  inc_ver_and
end


platform :ios do
  version = package['version']
  build_number = nil

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'th.co.cargolink.mobile', type: 'development', readonly: true)
    match(app_identifier: 'th.co.cargolink.mobile', type: 'appstore', readonly: true)
  end

  desc 'Update version code and version number'
  lane :bump_version do

    
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    bump_version
    build_app(workspace: "./ios/CargoLinkMobile.xcworkspace", scheme: "CargoLinkMobile")
    # gym(scheme: 'CargoLinkMobile', project: './ios/CargoLinkMobile.xcodeproj')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
  end

  after_all do |lane|
    clean_build_artifacts
    tag_string = "ios-v" + version + "-b" + build_number
    commit_version_bump(message: 'Bump build (ios) ' + tag_string, xcodeproj: './ios/CargoLinkMobile.xcodeproj')
    add_git_tag(tag: tag_string)
  end
end

platform :android do
  desc 'Build the Android application.'
  version = package['version']
  build_number = nil

  desc 'Update version code and version number'
  lane :bump_version do

  end

  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    bump_version
    build
    supply(track: 'beta', track_promote_to: 'beta')
  end

  after_all do |lane|
    tag_string = "android-v" + version + "-b" + build_number
    git_commit(path: ".", message: "Bump build (android) " + tag_string)
    add_git_tag(tag: tag_string)
  end
end

after_all do
  push_to_git_remote
end
