interface vehicle {
    label: string
    value: string
}
export const vehicleEn: Array<vehicle> = [
    { label: 'Others', value: 'อื่นๆ' },
    { label: '4 Wheels - High Stall Truck', value: '4 Wheels - High Stall Truck', },
    { label: '4 Wheels - Low Stall Truck', value: '4 Wheels - Low Stall Truck', },
    { label: '4 Wheels - Flat Bed', value: '4 Wheels - Flat Bed', },
    { label: '4 wheels - Cabinet Truck', value: '4 wheels - Cabinet Truck', },
    { label: '4 wheels - Cabinet Truck + Temperature Controlled', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
    { label: '4 Wheels - Cap Truck', value: '4 Wheels - Cap Truck', },
    { label: '4 wheels - Truck', value: '4 wheels - Truck', },
    { label: '6 wheels - Stall Truck', value: '6 wheels - Stall Truck', },
    { label: '6 wheels - Liquid Truck', value: '6 wheels - Liquid Truck', },
    { label: '6 Wheels - Cabinet Truck', value: '6 Wheels - Cabinet Truck', },
    { label: '6 wheels - Flat Bed', value: '6 wheels - Flat Bed', },
    { label: '6 wheels - Pickup Truck', value: '6 wheels - Pickup Truck', },
    { label: '6 Wheels - Cabinet Truck - Temperature Controlled', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: '6 Wheels - Crane', value: '6 Wheels - Crane', },
    { label: '10 Wheels - Crane', value: '10 Wheels - Crane', },
    { label: '10 Wheels - Stall + Dump Truck', value: '10 Wheels - Stall + Dump Truck', },
    { label: '10 Wheels - Chemical Tanker', value: '10 Wheels - Chemical Tanker', },
    { label: '10 Wheels - Stall Truck', value: '10 Wheels - Stall Truck', },
    { label: '10 Wheels - Cabinet Truck', value: '10 Wheels - Cabinet Truck', },
    { label: '10 Wheels - Flat Bed', value: '10 Wheels - Flat Bed', },
    { label: '10 Wheels - Liquid Tanker', value: '10 Wheels - Liquid Tanker', },
    { label: '10 Wheels - Cabinet Truck - Temperature Controlled', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: '10 wheels - Fuel Tanker', value: '10 wheels - Fuel Tanker', },
    { label: '18 Wheels - Flat Bed', value: '18 Wheels - Flat Bed', },
    { label: 'Semi - Trailer Cement Tanker', value: 'Semi - Trailer Cement Tanker', },
    { label: '40” Trailer - Cabinet Truck', value: '40” Trailer - Cabinet Truck', },
    { label: '40” Trailer - Cabinet Truck - Temperature Controlled', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
    { label: '40” Trailer 18 Wheels - Stall Truck', value: '40” Trailer 18 Wheels - Stall Truck', },
    { label: '20” Trailer 18 Wheels - Stall Truck + Dump', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: '40” Trailer 18 Wheels - Stall Truck + Dump', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: '18 Wheels - Skeleton Semi Trailer', value: '18 Wheels - Skeleton Semi Trailer', },
    { label: 'Tractor Head Truck', value: 'Tractor Head Truck', },
    { label: 'Car Carrier Trailer', value: 'Car Carrier Trailer', },
    { label: 'Bike Carrier Truck', value: 'Bike Carrier Truck', },
    { label: '20” Trailer, 18 Wheels - Cabinet Truck', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
    { label: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
    { label: '20” Trailer 18 Wheels - Stall Truck', value: '20” Trailer 18 Wheels - Stall Truck', },
    { label: 'Trailer 22 wheels Side Curtain', value: 'Trailer 22 wheels Side Curtain', },
    { label: '20 wheels Side Curtain', value: '20 wheels Side Curtain' }]


export const vehicleTh: Array<vehicle> = [
    { label: 'อื่นๆ', value: 'Others', },
    { label: 'รถกระบะ 4 ล้อคอกสูง', value: '4 Wheels - High Stall Truck', },
    { label: 'รถกระบะ 4 ล้อคอกเตี้ย', value: '4 Wheels - Low Stall Truck', },
    { label: 'รถกระบะ 4 ล้อพื้นเรียบ', value: '4 Wheels - Flat Bed', },
    { label: 'รถกระบะ 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck', },
    { label: 'รถกระบะห้องเย็น 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
    { label: 'รถกระบะ 4 ล้อหลังคาสูงทึบ', value: '4 Wheels - Cap Truck', },
    { label: 'รถกระบะ 4 ล้อ', value: '4 wheels - Truck', },
    { label: 'รถ 6 ล้อตู้คอก', value: '6 wheels - Stall Truck', },
    { label: 'รถบรรทุกของเหลว 6 ล้อ', value: '6 wheels - Liquid Truck', },
    { label: 'รถ 6 ล้อ ตู้ทึบ', value: '6 Wheels - Cabinet Truck', },
    { label: 'รถ 6 ล้อพื้นเรียบ', value: '6 wheels - Flat Bed', },
    { label: 'รถ 6 ล้อ กระบะ', value: '6 wheels - Pickup Truck', },
    { label: 'รถห้องเย็น 6 ล้อตู้ทึบ', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถเครน 6 ล้อ', value: '6 Wheels - Crane', },
    { label: 'รถเครน 10 ล้อ', value: '10 Wheels - Crane', },
    { label: 'รถ 10 ล้อคอกดัมพ์', value: '10 Wheels - Stall + Dump Truck', },
    { label: 'รถ 10 ล้อ เคมีภัณฑ์', value: '10 Wheels - Chemical Tanker', },
    { label: 'รถ 10 ล้อคอก', value: '10 Wheels - Stall Truck', },
    { label: 'รถ 10 ล้อ ตู้ทึบ', value: '10 Wheels - Cabinet Truck', },
    { label: 'รถ 10 ล้อ พื้นเรียบ', value: '10 Wheels - Flat Bed', },
    { label: 'รถ 10 ล้อบรรทุกของเหลว', value: '10 Wheels - Liquid Tanker', },
    { label: 'รถห้องเย็น 10 ล้อตู้ทึบ', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถ 10 ล้อ บรรทุกน้ำมัน', value: '10 wheels - Fuel Tanker', },
    { label: 'รถหัวลาก 18 ล้อ พื้นเรียบ', value: '18 Wheels - Flat Bed', },
    { label: 'รถบรรทุกปูนซีเมนต์ประเภทผง', value: 'Semi - Trailer Cement Tanker', },
    { label: 'รถหัวลาก 18 ล้อ ตู้ทึบ 40 ฟุต', value: '40” Trailer - Cabinet Truck', },
    { label: 'รถเทรเลอร์คอนเทรนเนอร์ ห้องเย็น 40 ฟุต', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถพ่วงคอกดัมพ์', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'รถพ่วงดัมพ์ 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'เทรลเลอร์ก้างปลา', value: '18 Wheels - Skeleton Semi Trailer', },
    { label: 'รถหัวลาก', value: 'Tractor Head Truck', },
    { label: 'รถบรรทุกรถ', value: 'Car Carrier Trailer', },
    { label: 'รถบรรทุกจักรยานยนต์', value: 'Bike Carrier Truck', },
    { label: 'รถพ่วง 18 ล้อตู้ทึบ 20 ฟุต', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
    { label: 'รถพ่วงตู้ทึบ 20 ฟุต', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 20 ฟุต', value: '20” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถเทรเลอร์เปิดข้างผ้าม่าน', value: 'Trailer 22 wheels Side Curtain', },
    { label: 'รถพ่วงเปิดข้างผ้าม่าน', value: '20 wheels Side Curtain' }]

interface region {
    label: string
    value: string
}
export const regionListEn: Array<region> = [
    { label: "north", value: "north" },
    { label: "north-east", value: "north-east" },
    { label: "south", value: "south" },
    { label: "west", value: "west" },
    { label: "center", value: "center" },
    { label: "east", value: "east" },
    { label: "all region", value: "all" },
]

export const regionListTh: Array<region> = [
    { label: "ภาคเหนือ", value: "north" },
    { label: "ภาคตะวันออกเฉียงเหนือ", value: "north-east" },
    { label: "ภาคใต้", value: "south" },
    { label: "ภาคตะวันตก", value: "west" },
    { label: "ภาคกลาง", value: "center" },
    { label: "ภาคตะวันออก", value: "east" },
    { label: "ทั่วประเทศ", value: "all" },
]

interface province {
    label: string
    value: string
    region: string
}

export const provinceListTh: Array<province> = [
    { "label": "กรุงเทพมหานคร", "value": "Bangkok", region: 'center' },
    { "label": "สมุทรปราการ", "value": "Samut Prakarn", region: 'east' },
    { "label": "นนทบุรี", "value": "Nonthaburi", region: 'center' },
    { "label": "ปทุมธานี", "value": "Pathum Thani", region: 'center' },
    { "label": "พระนครศรีอยุธยา", "value": "Phra Nakhon Si Ayutthaya", region: 'center' },
    { "label": "อ่างทอง", "value": "Ang Thong", region: 'center' },
    { "label": "ลพบุรี", "value": "Lop Buri", region: 'center' },
    { "label": "สิงห์บุรี", "value": "Sing Buri", region: 'center' },
    { "label": "ชัยนาท", "value": "Chai Nat", region: 'center' },
    { "label": "สระบุรี", "value": "Saraburi", region: 'center' },
    { "label": "นครนายก", "value": "Nakhon Nayok", region: 'center' },
    { "label": "ชลบุรี", "value": "Chon Buri", region: 'east' },
    { "label": "ระยอง", "value": "Rayong", region: 'east' },
    { "label": "จันทบุรี", "value": "Chanthaburi", region: 'east' },
    { "label": "ตราด", "value": "Trat", region: 'east' },
    { "label": "ฉะเชิงเทรา", "value": "Chachoengsao", region: 'east' },
    { "label": "ปราจีนบุรี", "value": "Prachin Buri", region: 'east' },
    { "label": "สระแก้ว", "value": "Sa kaeo", region: 'east' },
    { "label": "นครราชสีมา", "value": "Nakhon Ratchasima", region: 'north-east' },
    { "label": "บุรีรัมย์", "value": "Buri Ram", region: 'north-east' },
    { "label": "สุรินทร์", "value": "Surin", region: 'north-east' },
    { "label": "ศรีสะเกษ", "value": "Si Sa Ket", region: 'north-east' },
    { "label": "อุบลราชธานี", "value": "Ubon Ratchathani", region: 'north-east' },
    { "label": "ยโสธร", "value": "Yasothon", region: 'north-east' },
    { "label": "ชัยภูมิ", "value": "Chaiyaphum", region: 'north-east' },
    { "label": "อำนาจเจริญ", "value": "Amnat Charoen", region: 'north-east' },
    { "label": "บึงกาฬ", "value": "Bueng Kan", region: 'north-east' },
    { "label": "หนองบัวลำภู", "value": "Nong Bua Lam Phu", region: 'north-east' },
    { "label": "ขอนแก่น", "value": "Khon Kaen", region: 'north-east' },
    { "label": "อุดรธานี", "value": "Udon Thani", region: 'north-east' },
    { "label": "เลย", "value": "Loei", region: 'north-east' },
    { "label": "หนองคาย", "value": "Nong Khai", region: 'north-east' },
    { "label": "มหาสารคาม", "value": "Maha Sarakham", region: 'north-east' },
    { "label": "ร้อยเอ็ด", "value": "Roi Et", region: 'north-east' },
    { "label": "กาฬสินธุ์", "value": "Kalasin", region: 'north-east' },
    { "label": "สกลนคร", "value": "Sakon Nakhon", region: 'north-east' },
    { "label": "นครพนม", "value": "Nakhon Phanom", region: 'north-east' },
    { "label": "มุกดาหาร", "value": "Mukdahan", region: 'north-east' },
    { "label": "เชียงใหม่", "value": "Chiang Mai", region: 'north' },
    { "label": "ลำพูน", "value": "Lamphun", region: 'north' },
    { "label": "ลำปาง", "value": "Lampang", region: 'north' },
    { "label": "อุตรดิตถ์", "value": "Uttaradit", region: 'north' },
    { "label": "แพร่", "value": "Phrae", region: 'north' },
    { "label": "น่าน", "value": "Nan", region: 'north' },
    { "label": "พะเยา", "value": "Phayao", region: 'north' },
    { "label": "เชียงราย", "value": "Chiang Rai", region: 'north' },
    { "label": "แม่ฮ่องสอน", "value": "Mae Hong Son", region: 'north' },
    { "label": "นครสวรรค์", "value": "Nakhon Sawan", region: 'center' },
    { "label": "อุทัยธานี", "value": "Uthai Thani", region: 'center' },
    { "label": "กำแพงเพชร", "value": "Kamphaeng Phet", region: 'center' },
    { "label": "ตาก", "value": "Tak", region: 'west' },
    { "label": "สุโขทัย", "value": "Sukhothai", region: 'center' },
    { "label": "พิษณุโลก", "value": "Phitsanulok", region: 'center' },
    { "label": "พิจิตร", "value": "Phichit", region: 'center' },
    { "label": "เพชรบูรณ์", "value": "Phetchabun", region: 'center' },
    { "label": "ราชบุรี", "value": "Ratchaburi", region: 'west' },
    { "label": "กาญจนบุรี", "value": "Kanchanaburi", region: 'west' },
    { "label": "สุพรรณบุรี", "value": "Suphan Buri", region: 'center' },
    { "label": "นครปฐม", "value": "Nakhon Pathom", region: 'center' },
    { "label": "สมุทรสาคร", "value": "Samut Sakhon", region: 'center' },
    { "label": "สมุทรสงคราม", "value": "Samut Songkhram", region: 'center' },
    { "label": "เพชรบุรี", "value": "Phetchaburi", region: 'west' },
    { "label": "ประจวบคีรีขันธ์", "value": "Prachuap Khiri Khan", region: 'west' },
    { "label": "นครศรีธรรมราช", "value": "Nakhon Si Thammarat", region: 'south' },
    { "label": "กระบี่", "value": "Krabi", region: 'south' },
    { "label": "พังงา", "value": "Phang-nga", region: 'south' },
    { "label": "ภูเก็ต", "value": "Phuket", region: 'south' },
    { "label": "สุราษฎร์ธานี", "value": "Surat Thani", region: 'south' },
    { "label": "ระนอง", "value": "Ranong", region: 'south' },
    { "label": "ชุมพร", "value": "Chumphon", region: 'south' },
    { "label": "สงขลา", "value": "Songkhla", region: 'south' },
    { "label": "สตูล", "value": "Satun", region: 'south' },
    { "label": "ตรัง", "value": "Trang", region: 'south' },
    { "label": "พัทลุง", "value": "Phatthalung", region: 'south' },
    { "label": "ปัตตานี", "value": "Pattani", region: 'south' },
    { "label": "ยะลา", "value": "Yala", region: 'south' },
    { "label": "นราธิวาส", "value": "Narathiwat", region: 'south' },
]

export const provinceListEn: Array<province> = [
    { "label": "Bangkok", "value": "Bangkok", region: 'center' },
    { "label": "Samut Prakarn", "value": "Samut Prakarn", region: 'east' },
    { "label": "Nonthaburi", "value": "Nonthaburi", region: 'center' },
    { "label": "Pathum Thani", "value": "Pathum Thani", region: 'center' },
    { "label": "Phra Nakhon Si Ayutthaya", "value": "Phra Nakhon Si Ayutthaya", region: 'center' },
    { "label": "Ang Thong", "value": "Ang Thong", region: 'center' },
    { "label": "Lop Buri", "value": "Lop Buri", region: 'center' },
    { "label": "Sing Buri", "value": "Sing Buri", region: 'center' },
    { "label": "Chai Nat", "value": "Chai Nat", region: 'center' },
    { "label": "Saraburi", "value": "Saraburi", region: 'center' },
    { "label": "Nakhon Nayok", "value": "Nakhon Nayok", region: 'center' },
    { "label": "Chon Buri", "value": "Chon Buri", region: 'east' },
    { "label": "Rayong", "value": "Rayong", region: 'east' },
    { "label": "Chanthaburi", "value": "Chanthaburi", region: 'east' },
    { "label": "Trat", "value": "Trat", region: 'east' },
    { "label": "Chachoengsao", "value": "Chachoengsao", region: 'east' },
    { "label": "Prachin Buri", "value": "Prachin Buri", region: 'east' },
    { "label": "Sa kaeo", "value": "Sa kaeo", region: 'east' },
    { "label": "Nakhon Ratchasima", "value": "Nakhon Ratchasima", region: 'north-east' },
    { "label": "Buri Ram", "value": "Buri Ram", region: 'north-east' },
    { "label": "Surin", "value": "Surin", region: 'north-east' },
    { "label": "Si Sa Ket", "value": "Si Sa Ket", region: 'north-east' },
    { "label": "Ubon Ratchathani", "value": "Ubon Ratchathani", region: 'north-east' },
    { "label": "Yasothon", "value": "Yasothon", region: 'north-east' },
    { "label": "Chaiyaphum", "value": "Chaiyaphum", region: 'north-east' },
    { "label": "Amnat Charoen", "value": "Amnat Charoen", region: 'north-east' },
    { "label": "Bueng Kan", "value": "Bueng Kan", region: 'north-east' },
    { "label": "Nong Bua Lam Phu", "value": "Nong Bua Lam Phu", region: 'north-east' },
    { "label": "Khon Kaen", "value": "Khon Kaen", region: 'north-east' },
    { "label": "Udon Thani", "value": "Udon Thani", region: 'north-east' },
    { "label": "Loei", "value": "Loei", region: 'north-east' },
    { "label": "Nong Khai", "value": "Nong Khai", region: 'north-east' },
    { "label": "Maha Sarakham", "value": "Maha Sarakham", region: 'north-east' },
    { "label": "Roi Et", "value": "Roi Et", region: 'north-east' },
    { "label": "Kalasin", "value": "Kalasin", region: 'north-east' },
    { "label": "Sakon Nakhon", "value": "Sakon Nakhon", region: 'north-east' },
    { "label": "Nakhon Phanom", "value": "Nakhon Phanom", region: 'north-east' },
    { "label": "Mukdahan", "value": "Mukdahan", region: 'north-east' },
    { "label": "Chiang Mai", "value": "Chiang Mai", region: 'north' },
    { "label": "Lamphun", "value": "Lamphun", region: 'north' },
    { "label": "Lampang", "value": "Lampang", region: 'north' },
    { "label": "Uttaradit", "value": "Uttaradit", region: 'north' },
    { "label": "Phrae", "value": "Phrae", region: 'north' },
    { "label": "Nan", "value": "Nan", region: 'north' },
    { "label": "Phayao", "value": "Phayao", region: 'north' },
    { "label": "Chiang Rai", "value": "Chiang Rai", region: 'north' },
    { "label": "Mae Hong Son", "value": "Mae Hong Son", region: 'north' },
    { "label": "Nakhon Sawan", "value": "Nakhon Sawan", region: 'center' },
    { "label": "Uthai Thani", "value": "Uthai Thani", region: 'center' },
    { "label": "Kamphaeng Phet", "value": "Kamphaeng Phet", region: 'center' },
    { "label": "Tak", "value": "Tak", region: 'west' },
    { "label": "Sukhothai", "value": "Sukhothai", region: 'center' },
    { "label": "Phitsanulok", "value": "Phitsanulok", region: 'center' },
    { "label": "Phichit", "value": "Phichit", region: 'center' },
    { "label": "Phetchabun", "value": "Phetchabun", region: 'center' },
    { "label": "Ratchaburi", "value": "Ratchaburi", region: 'west' },
    { "label": "Kanchanaburi", "value": "Kanchanaburi", region: 'west' },
    { "label": "Suphan Buri", "value": "Suphan Buri", region: 'center' },
    { "label": "Nakhon Pathom", "value": "Nakhon Pathom", region: 'center' },
    { "label": "Samut Sakhon", "value": "Samut Sakhon", region: 'center' },
    { "label": "Samut Songkhram", "value": "Samut Songkhram", region: 'center' },
    { "label": "Phetchaburi", "value": "Phetchaburi", region: 'west' },
    { "label": "Prachuap Khiri Khan", "value": "Prachuap Khiri Khan", region: 'west' },
    { "label": "Nakhon Si Thammarat", "value": "Nakhon Si Thammarat", region: 'south' },
    { "label": "Krabi", "value": "Krabi", region: 'south' },
    { "label": "Phang-nga", "value": "Phang-nga", region: 'south' },
    { "label": "Phuket", "value": "Phuket", region: 'south' },
    { "label": "Surat Thani", "value": "Surat Thani", region: 'south' },
    { "label": "Ranong", "value": "Ranong", region: 'south' },
    { "label": "Chumphon", "value": "Chumphon", region: 'south' },
    { "label": "Songkhla", "value": "Songkhla", region: 'south' },
    { "label": "Satun", "value": "Satun", region: 'south' },
    { "label": "Trang", "value": "Trang", region: 'south' },
    { "label": "Phatthalung", "value": "Phatthalung", region: 'south' },
    { "label": "Pattani", "value": "Pattani", region: 'south' },
    { "label": "Yala", "value": "Yala", region: 'south' },
    { "label": "Narathiwat", "value": "Narathiwat", region: 'south' },
]
