interface vehicle {
    label: string
    value: string
}
export const vehicleEn: Array<vehicle> = [
    { label: 'Others', value: 'อื่นๆ' },
    { label: '4 Wheels - High Stall Truck', value: '4 Wheels - High Stall Truck', },
    { label: '4 Wheels - Low Stall Truck', value: '4 Wheels - Low Stall Truck', },
    { label: '4 Wheels - Flat Bed', value: '4 Wheels - Flat Bed', },
    { label: '4 wheels - Cabinet Truck', value: '4 wheels - Cabinet Truck', },
    { label: '4 wheels - Cabinet Truck + Temperature Controlled', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
    { label: '4 Wheels - Cap Truck', value: '4 Wheels - Cap Truck', },
    { label: '4 wheels - Truck', value: '4 wheels - Truck', },
    { label: '6 wheels - Stall Truck', value: '6 wheels - Stall Truck', },
    { label: '6 wheels - Liquid Truck', value: '6 wheels - Liquid Truck', },
    { label: '6 Wheels - Cabinet Truck', value: '6 Wheels - Cabinet Truck', },
    { label: '6 wheels - Flat Bed', value: '6 wheels - Flat Bed', },
    { label: '6 wheels - Pickup Truck', value: '6 wheels - Pickup Truck', },
    { label: '6 Wheels - Cabinet Truck - Temperature Controlled', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: '6 Wheels - Crane', value: '6 Wheels - Crane', },
    { label: '10 Wheels - Crane', value: '10 Wheels - Crane', },
    { label: '10 Wheels - Stall + Dump Truck', value: '10 Wheels - Stall + Dump Truck', },
    { label: '10 Wheels - Chemical Tanker', value: '10 Wheels - Chemical Tanker', },
    { label: '10 Wheels - Stall Truck', value: '10 Wheels - Stall Truck', },
    { label: '10 Wheels - Cabinet Truck', value: '10 Wheels - Cabinet Truck', },
    { label: '10 Wheels - Flat Bed', value: '10 Wheels - Flat Bed', },
    { label: '10 Wheels - Liquid Tanker', value: '10 Wheels - Liquid Tanker', },
    { label: '10 Wheels - Cabinet Truck - Temperature Controlled', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: '10 wheels - Fuel Tanker', value: '10 wheels - Fuel Tanker', },
    { label: '18 Wheels - Flat Bed', value: '18 Wheels - Flat Bed', },
    { label: 'Semi - Trailer Cement Tanker', value: 'Semi - Trailer Cement Tanker', },
    { label: '40” Trailer - Cabinet Truck', value: '40” Trailer - Cabinet Truck', },
    { label: '40” Trailer - Cabinet Truck - Temperature Controlled', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
    { label: '40” Trailer 18 Wheels - Stall Truck', value: '40” Trailer 18 Wheels - Stall Truck', },
    { label: '20” Trailer 18 Wheels - Stall Truck + Dump', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: '40” Trailer 18 Wheels - Stall Truck + Dump', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: '18 Wheels - Skeleton Semi Trailer', value: '18 Wheels - Skeleton Semi Trailer', },
    { label: 'Tractor Head Truck', value: 'Tractor Head Truck', },
    { label: 'Car Carrier Trailer', value: 'Car Carrier Trailer', },
    { label: 'Bike Carrier Truck', value: 'Bike Carrier Truck', },
    { label: '20” Trailer, 18 Wheels - Cabinet Truck', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
    { label: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
    { label: '20” Trailer 18 Wheels - Stall Truck', value: '20” Trailer 18 Wheels - Stall Truck', },
    { label: 'Trailer 22 wheels Side Curtain', value: 'Trailer 22 wheels Side Curtain', },
    { label: '20 wheels Side Curtain', value: '20 wheels Side Curtain' }]


export const vehicleTh: Array<vehicle> = [
    { label: 'อื่นๆ', value: 'Others', },
    { label: 'รถกระบะ 4 ล้อคอกสูง', value: '4 Wheels - High Stall Truck', },
    { label: 'รถกระบะ 4 ล้อคอกเตี้ย', value: '4 Wheels - Low Stall Truck', },
    { label: 'รถกระบะ 4 ล้อพื้นเรียบ', value: '4 Wheels - Flat Bed', },
    { label: 'รถกระบะ 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck', },
    { label: 'รถกระบะห้องเย็น 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
    { label: 'รถกระบะ 4 ล้อหลังคาสูงทึบ', value: '4 Wheels - Cap Truck', },
    { label: 'รถกระบะ 4 ล้อ', value: '4 wheels - Truck', },
    { label: 'รถ 6 ล้อตู้คอก', value: '6 wheels - Stall Truck', },
    { label: 'รถบรรทุกของเหลว 6 ล้อ', value: '6 wheels - Liquid Truck', },
    { label: 'รถ 6 ล้อ ตู้ทึบ', value: '6 Wheels - Cabinet Truck', },
    { label: 'รถ 6 ล้อพื้นเรียบ', value: '6 wheels - Flat Bed', },
    { label: 'รถ 6 ล้อ กระบะ', value: '6 wheels - Pickup Truck', },
    { label: 'รถห้องเย็น 6 ล้อตู้ทึบ', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถเครน 6 ล้อ', value: '6 Wheels - Crane', },
    { label: 'รถเครน 10 ล้อ', value: '10 Wheels - Crane', },
    { label: 'รถ 10 ล้อคอกดัมพ์', value: '10 Wheels - Stall + Dump Truck', },
    { label: 'รถ 10 ล้อ เคมีภัณฑ์', value: '10 Wheels - Chemical Tanker', },
    { label: 'รถ 10 ล้อคอก', value: '10 Wheels - Stall Truck', },
    { label: 'รถ 10 ล้อ ตู้ทึบ', value: '10 Wheels - Cabinet Truck', },
    { label: 'รถ 10 ล้อ พื้นเรียบ', value: '10 Wheels - Flat Bed', },
    { label: 'รถ 10 ล้อบรรทุกของเหลว', value: '10 Wheels - Liquid Tanker', },
    { label: 'รถห้องเย็น 10 ล้อตู้ทึบ', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถ 10 ล้อ บรรทุกน้ำมัน', value: '10 wheels - Fuel Tanker', },
    { label: 'รถหัวลาก 18 ล้อ พื้นเรียบ', value: '18 Wheels - Flat Bed', },
    { label: 'รถบรรทุกปูนซีเมนต์ประเภทผง', value: 'Semi - Trailer Cement Tanker', },
    { label: 'รถหัวลาก 18 ล้อ ตู้ทึบ 40 ฟุต', value: '40” Trailer - Cabinet Truck', },
    { label: 'รถเทรเลอร์คอนเทรนเนอร์ ห้องเย็น 40 ฟุต', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถพ่วงคอกดัมพ์', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'รถพ่วงดัมพ์ 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'เทรลเลอร์ก้างปลา', value: '18 Wheels - Skeleton Semi Trailer', },
    { label: 'รถหัวลาก', value: 'Tractor Head Truck', },
    { label: 'รถบรรทุกรถ', value: 'Car Carrier Trailer', },
    { label: 'รถบรรทุกจักรยานยนต์', value: 'Bike Carrier Truck', },
    { label: 'รถพ่วง 18 ล้อตู้ทึบ 20 ฟุต', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
    { label: 'รถพ่วงตู้ทึบ 20 ฟุต', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 20 ฟุต', value: '20” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถเทรเลอร์เปิดข้างผ้าม่าน', value: 'Trailer 22 wheels Side Curtain', },
    { label: 'รถพ่วงเปิดข้างผ้าม่าน', value: '20 wheels Side Curtain' }]

interface region {
    label: string
    value: string
}
export const regionListEn: Array<region> = [
    { label: "north", value: "north" },
    { label: "north-east", value: "north-east" },
    { label: "south", value: "south" },
    { label: "west", value: "west" },
    { label: "center", value: "center" },
]

export const regionListTh: Array<region> = [
    { label: "ภาคเหนือ", value: "north" },
    { label: "ภาคตะวันออกเฉียงเหนือ", value: "north-east" },
    { label: "ภาคใต้", value: "south" },
    { label: "ภาคตะวันตก", value: "west" },
    { label: "ภาคกลาง", value: "center" },
]

interface province {
    label: string
    value: string
}

export const provinceListTh: Array<province> = [{ "label": "กรุงเทพมหานคร", "value": "Bangkok" },
{ "label": "สมุทรปราการ", "value": "Samut Prakarn" },
{ "label": "นนทบุรี", "value": "Nonthaburi" },
{ "label": "ปทุมธานี", "value": "Pathum Thani" },
{ "label": "พระนครศรีอยุธยา", "value": "Phra Nakhon Si Ayutthaya" },
{ "label": "อ่างทอง", "value": "Ang Thong" },
{ "label": "ลพบุรี", "value": "Lop Buri" },
{ "label": "สิงห์บุรี", "value": "Sing Buri" },
{ "label": "ชัยนาท", "value": "Chai Nat" },
{ "label": "สระบุรี", "value": "Saraburi" },
{ "label": "ชลบุรี", "value": "Chon Buri" },
{ "label": "ระยอง", "value": "Rayong" },
{ "label": "จันทบุรี", "value": "Chanthaburi" },
{ "label": "ตราด", "value": "Trat" },
{ "label": "ฉะเชิงเทรา", "value": "Chachoengsao" },
{ "label": "ปราจีนบุรี", "value": "Prachin Buri" },
{ "label": "นครนายก", "value": "Nakhon Nayok" },
{ "label": "สระแก้ว", "value": "Sa kaeo" },
{ "label": "นครราชสีมา", "value": "Nakhon Ratchasima" },
{ "label": "บุรีรัมย์", "value": "Buri Ram" },
{ "label": "สุรินทร์", "value": "Surin" },
{ "label": "ศรีสะเกษ", "value": "Si Sa Ket" },
{ "label": "อุบลราชธานี", "value": "Ubon Ratchathani" },
{ "label": "ยโสธร", "value": "Yasothon" },
{ "label": "ชัยภูมิ", "value": "Chaiyaphum" },
{ "label": "อำนาจเจริญ", "value": "Amnat Charoen" },
{ "label": "บึงกาฬ", "value": "Bueng Kan" },
{ "label": "หนองบัวลำภู", "value": "Nong Bua Lam Phu" },
{ "label": "ขอนแก่น", "value": "Khon Kaen" },
{ "label": "อุดรธานี", "value": "Udon Thani" },
{ "label": "เลย", "value": "Loei" },
{ "label": "หนองคาย", "value": "Nong Khai" },
{ "label": "มหาสารคาม", "value": "Maha Sarakham" },
{ "label": "ร้อยเอ็ด", "value": "Roi Et" },
{ "label": "กาฬสินธุ์", "value": "Kalasin" },
{ "label": "สกลนคร", "value": "Sakon Nakhon" },
{ "label": "นครพนม", "value": "Nakhon Phanom" },
{ "label": "มุกดาหาร", "value": "Mukdahan" },
{ "label": "เชียงใหม่", "value": "Chiang Mai" },
{ "label": "ลำพูน", "value": "Lamphun" },
{ "label": "ลำปาง", "value": "Lampang" },
{ "label": "อุตรดิตถ์", "value": "Uttaradit" },
{ "label": "แพร่", "value": "Phrae" },
{ "label": "น่าน", "value": "Nan" },
{ "label": "พะเยา", "value": "Phayao" },
{ "label": "เชียงราย", "value": "Chiang Rai" },
{ "label": "แม่ฮ่องสอน", "value": "Mae Hong Son" },
{ "label": "นครสวรรค์", "value": "Nakhon Sawan" },
{ "label": "อุทัยธานี", "value": "Uthai Thani" },
{ "label": "กำแพงเพชร", "value": "Kamphaeng Phet" },
{ "label": "ตาก", "value": "Tak" },
{ "label": "สุโขทัย", "value": "Sukhothai" },
{ "label": "พิษณุโลก", "value": "Phitsanulok" },
{ "label": "พิจิตร", "value": "Phichit" },
{ "label": "เพชรบูรณ์", "value": "Phetchabun" },
{ "label": "ราชบุรี", "value": "Ratchaburi" },
{ "label": "กาญจนบุรี", "value": "Kanchanaburi" },
{ "label": "สุพรรณบุรี", "value": "Suphan Buri" },
{ "label": "นครปฐม", "value": "Nakhon Pathom" },
{ "label": "สมุทรสาคร", "value": "Samut Sakhon" },
{ "label": "สมุทรสงคราม", "value": "Samut Songkhram" },
{ "label": "เพชรบุรี", "value": "Phetchaburi" },
{ "label": "ประจวบคีรีขันธ์", "value": "Prachuap Khiri Khan" },
{ "label": "นครศรีธรรมราช", "value": "Nakhon Si Thammarat" },
{ "label": "กระบี่", "value": "Krabi" },
{ "label": "พังงา", "value": "Phang-nga" },
{ "label": "ภูเก็ต", "value": "Phuket" },
{ "label": "สุราษฎร์ธานี", "value": "Surat Thani" },
{ "label": "ระนอง", "value": "Ranong" },
{ "label": "ชุมพร", "value": "Chumphon" },
{ "label": "สงขลา", "value": "Songkhla" },
{ "label": "สตูล", "value": "Satun" },
{ "label": "ตรัง", "value": "Trang" },
{ "label": "พัทลุง", "value": "Phatthalung" },
{ "label": "ปัตตานี", "value": "Pattani" },
{ "label": "ยะลา", "value": "Yala" },
{ "label": "นราธิวาส", "value": "Narathiwat" }
]

export const provinceListEn: Array<province> = [{ "label": "Bangkok", "value": "Bangkok" },
{ "label": "Samut Prakarn", "value": "Samut Prakarn" },
{ "label": "Nonthaburi", "value": "Nonthaburi" },
{ "label": "Pathum Thani", "value": "Pathum Thani" },
{ "label": "Phra Nakhon Si Ayutthaya", "value": "Phra Nakhon Si Ayutthaya" },
{ "label": "Ang Thong", "value": "Ang Thong" },
{ "label": "Lop Buri", "value": "Lop Buri" },
{ "label": "Sing Buri", "value": "Sing Buri" },
{ "label": "Chai Nat", "value": "Chai Nat" },
{ "label": "Saraburi", "value": "Saraburi" },
{ "label": "Chon Buri", "value": "Chon Buri" },
{ "label": "Rayong", "value": "Rayong" },
{ "label": "Chanthaburi", "value": "Chanthaburi" },
{ "label": "Trat", "value": "Trat" },
{ "label": "Chachoengsao", "value": "Chachoengsao" },
{ "label": "Prachin Buri", "value": "Prachin Buri" },
{ "label": "Nakhon Nayok", "value": "Nakhon Nayok" },
{ "label": "Sa kaeo", "value": "Sa kaeo" },
{ "label": "Nakhon Ratchasima", "value": "Nakhon Ratchasima" },
{ "label": "Buri Ram", "value": "Buri Ram" },
{ "label": "Surin", "value": "Surin" },
{ "label": "Si Sa Ket", "value": "Si Sa Ket" },
{ "label": "Ubon Ratchathani", "value": "Ubon Ratchathani" },
{ "label": "Yasothon", "value": "Yasothon" },
{ "label": "Chaiyaphum", "value": "Chaiyaphum" },
{ "label": "Amnat Charoen", "value": "Amnat Charoen" },
{ "label": "Bueng Kan", "value": "Bueng Kan" },
{ "label": "Nong Bua Lam Phu", "value": "Nong Bua Lam Phu" },
{ "label": "Khon Kaen", "value": "Khon Kaen" },
{ "label": "Udon Thani", "value": "Udon Thani" },
{ "label": "Loei", "value": "Loei" },
{ "label": "Nong Khai", "value": "Nong Khai" },
{ "label": "Maha Sarakham", "value": "Maha Sarakham" },
{ "label": "Roi Et", "value": "Roi Et" },
{ "label": "Kalasin", "value": "Kalasin" },
{ "label": "Sakon Nakhon", "value": "Sakon Nakhon" },
{ "label": "Nakhon Phanom", "value": "Nakhon Phanom" },
{ "label": "Mukdahan", "value": "Mukdahan" },
{ "label": "Chiang Mai", "value": "Chiang Mai" },
{ "label": "Lamphun", "value": "Lamphun" },
{ "label": "Lampang", "value": "Lampang" },
{ "label": "Uttaradit", "value": "Uttaradit" },
{ "label": "Phrae", "value": "Phrae" },
{ "label": "Nan", "value": "Nan" },
{ "label": "Phayao", "value": "Phayao" },
{ "label": "Chiang Rai", "value": "Chiang Rai" },
{ "label": "Mae Hong Son", "value": "Mae Hong Son" },
{ "label": "Nakhon Sawan", "value": "Nakhon Sawan" },
{ "label": "Uthai Thani", "value": "Uthai Thani" },
{ "label": "Kamphaeng Phet", "value": "Kamphaeng Phet" },
{ "label": "Tak", "value": "Tak" },
{ "label": "Sukhothai", "value": "Sukhothai" },
{ "label": "Phitsanulok", "value": "Phitsanulok" },
{ "label": "Phichit", "value": "Phichit" },
{ "label": "Phetchabun", "value": "Phetchabun" },
{ "label": "Ratchaburi", "value": "Ratchaburi" },
{ "label": "Kanchanaburi", "value": "Kanchanaburi" },
{ "label": "Suphan Buri", "value": "Suphan Buri" },
{ "label": "Nakhon Pathom", "value": "Nakhon Pathom" },
{ "label": "Samut Sakhon", "value": "Samut Sakhon" },
{ "label": "Samut Songkhram", "value": "Samut Songkhram" },
{ "label": "Phetchaburi", "value": "Phetchaburi" },
{ "label": "Prachuap Khiri Khan", "value": "Prachuap Khiri Khan" },
{ "label": "Nakhon Si Thammarat", "value": "Nakhon Si Thammarat" },
{ "label": "Krabi", "value": "Krabi" },
{ "label": "Phang-nga", "value": "Phang-nga" },
{ "label": "Phuket", "value": "Phuket" },
{ "label": "Surat Thani", "value": "Surat Thani" },
{ "label": "Ranong", "value": "Ranong" },
{ "label": "Chumphon", "value": "Chumphon" },
{ "label": "Songkhla", "value": "Songkhla" },
{ "label": "Satun", "value": "Satun" },
{ "label": "Trang", "value": "Trang" },
{ "label": "Phatthalung", "value": "Phatthalung" },
{ "label": "Pattani", "value": "Pattani" },
{ "label": "Yala", "value": "Yala" },
{ "label": "Narathiwat", "value": "Narathiwat" }
]
