interface vehicle {
  label: string
  value: string
}
export const vehicleEn: Array<vehicle> = [
  { label: 'Others', value: 'อื่นๆ' },
  { label: '4 Wheels - High Stall Truck', value: '4 Wheels - High Stall Truck', },
  { label: '4 Wheels - Low Stall Truck', value: '4 Wheels - Low Stall Truck', },
  { label: '4 Wheels - Flat Bed', value: '4 Wheels - Flat Bed', },
  { label: '4 wheels - Cabinet Truck', value: '4 wheels - Cabinet Truck', },
  { label: '4 wheels - Cabinet Truck + Temperature Controlled', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
  { label: '4 Wheels - Cap Truck', value: '4 Wheels - Cap Truck', },
  { label: '4 wheels - Truck', value: '4 wheels - Truck', },
  { label: '6 wheels - Stall Truck', value: '6 wheels - Stall Truck', },
  { label: '6 wheels - Liquid Truck', value: '6 wheels - Liquid Truck', },
  { label: '6 Wheels - Cabinet Truck', value: '6 Wheels - Cabinet Truck', },
  { label: '6 wheels - Flat Bed', value: '6 wheels - Flat Bed', },
  { label: '6 wheels - Pickup Truck', value: '6 wheels - Pickup Truck', },
  { label: '6 Wheels - Cabinet Truck - Temperature Controlled', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
  { label: '6 Wheels - Crane', value: '6 Wheels - Crane', },
  { label: '10 Wheels - Crane', value: '10 Wheels - Crane', },
  { label: '10 Wheels - Stall + Dump Truck', value: '10 Wheels - Stall + Dump Truck', },
  { label: '10 Wheels - Chemical Tanker', value: '10 Wheels - Chemical Tanker', },
  { label: '10 Wheels - Stall Truck', value: '10 Wheels - Stall Truck', },
  { label: '10 Wheels - Cabinet Truck', value: '10 Wheels - Cabinet Truck', },
  { label: '10 Wheels - Flat Bed', value: '10 Wheels - Flat Bed', },
  { label: '10 Wheels - Liquid Tanker', value: '10 Wheels - Liquid Tanker', },
  { label: '10 Wheels - Cabinet Truck - Temperature Controlled', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
  { label: '10 wheels - Fuel Tanker', value: '10 wheels - Fuel Tanker', },
  { label: '18 Wheels - Flat Bed', value: '18 Wheels - Flat Bed', },
  { label: 'Semi - Trailer Cement Tanker', value: 'Semi - Trailer Cement Tanker', },
  { label: '40” Trailer - Cabinet Truck', value: '40” Trailer - Cabinet Truck', },
  { label: '40” Trailer - Cabinet Truck - Temperature Controlled', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
  { label: '40” Trailer 18 Wheels - Stall Truck', value: '40” Trailer 18 Wheels - Stall Truck', },
  { label: '20” Trailer 18 Wheels - Stall Truck + Dump', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
  { label: '40” Trailer 18 Wheels - Stall Truck + Dump', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
  { label: '18 Wheels - Skeleton Semi Trailer', value: '18 Wheels - Skeleton Semi Trailer', },
  { label: 'Tractor Head Truck', value: 'Tractor Head Truck', },
  { label: 'Car Carrier Trailer', value: 'Car Carrier Trailer', },
  { label: 'Bike Carrier Truck', value: 'Bike Carrier Truck', },
  { label: '20” Trailer, 18 Wheels - Cabinet Truck', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
  { label: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
  { label: '20” Trailer 18 Wheels - Stall Truck', value: '20” Trailer 18 Wheels - Stall Truck', },
  { label: 'Trailer 22 wheels Side Curtain', value: 'Trailer 22 wheels Side Curtain', },
  { label: '20 wheels Side Curtain', value: '20 wheels Side Curtain' }]


export const vehicleTh: Array<vehicle> = [
  { label: 'อื่นๆ', value: 'Others', },
  { label: 'รถกระบะ 4 ล้อคอกสูง', value: '4 Wheels - High Stall Truck', },
  { label: 'รถกระบะ 4 ล้อคอกเตี้ย', value: '4 Wheels - Low Stall Truck', },
  { label: 'รถกระบะ 4 ล้อพื้นเรียบ', value: '4 Wheels - Flat Bed', },
  { label: 'รถกระบะ 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck', },
  { label: 'รถกระบะห้องเย็น 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
  { label: 'รถกระบะ 4 ล้อหลังคาสูงทึบ', value: '4 Wheels - Cap Truck', },
  { label: 'รถกระบะ 4 ล้อ', value: '4 wheels - Truck', },
  { label: 'รถ 6 ล้อตู้คอก', value: '6 wheels - Stall Truck', },
  { label: 'รถบรรทุกของเหลว 6 ล้อ', value: '6 wheels - Liquid Truck', },
  { label: 'รถ 6 ล้อ ตู้ทึบ', value: '6 Wheels - Cabinet Truck', },
  { label: 'รถ 6 ล้อพื้นเรียบ', value: '6 wheels - Flat Bed', },
  { label: 'รถ 6 ล้อ กระบะ', value: '6 wheels - Pickup Truck', },
  { label: 'รถห้องเย็น 6 ล้อตู้ทึบ', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
  { label: 'รถเครน 6 ล้อ', value: '6 Wheels - Crane', },
  { label: 'รถเครน 10 ล้อ', value: '10 Wheels - Crane', },
  { label: 'รถ 10 ล้อคอกดัมพ์', value: '10 Wheels - Stall + Dump Truck', },
  { label: 'รถ 10 ล้อ เคมีภัณฑ์', value: '10 Wheels - Chemical Tanker', },
  { label: 'รถ 10 ล้อคอก', value: '10 Wheels - Stall Truck', },
  { label: 'รถ 10 ล้อ ตู้ทึบ', value: '10 Wheels - Cabinet Truck', },
  { label: 'รถ 10 ล้อ พื้นเรียบ', value: '10 Wheels - Flat Bed', },
  { label: 'รถ 10 ล้อบรรทุกของเหลว', value: '10 Wheels - Liquid Tanker', },
  { label: 'รถห้องเย็น 10 ล้อตู้ทึบ', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
  { label: 'รถ 10 ล้อ บรรทุกน้ำมัน', value: '10 wheels - Fuel Tanker', },
  { label: 'รถหัวลาก 18 ล้อ พื้นเรียบ', value: '18 Wheels - Flat Bed', },
  { label: 'รถบรรทุกปูนซีเมนต์ประเภทผง', value: 'Semi - Trailer Cement Tanker', },
  { label: 'รถหัวลาก 18 ล้อ ตู้ทึบ 40 ฟุต', value: '40” Trailer - Cabinet Truck', },
  { label: 'รถเทรลเลอร์คอนเทรนเนอร์ ห้องเย็น 40 ฟุต', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
  { label: 'รถพ่วงคอก 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck', },
  { label: 'รถพ่วงคอกดัมพ์', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
  { label: 'รถพ่วงดัมพ์ 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
  { label: 'เทรลเลอร์ก้างปลา', value: '18 Wheels - Skeleton Semi Trailer', },
  { label: 'รถหัวลาก', value: 'Tractor Head Truck', },
  { label: 'รถบรรทุกรถ', value: 'Car Carrier Trailer', },
  { label: 'รถบรรทุกจักรยานยนต์', value: 'Bike Carrier Truck', },
  { label: 'รถพ่วง 18 ล้อตู้ทึบ 20 ฟุต', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
  { label: 'รถพ่วงตู้ทึบ 20 ฟุต', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
  { label: 'รถพ่วงคอก 20 ฟุต', value: '20” Trailer 18 Wheels - Stall Truck', },
  { label: 'รถเทรลเลอร์เปิดข้างผ้าม่าน', value: 'Trailer 22 wheels Side Curtain', },
  { label: 'รถพ่วงเปิดข้างผ้าม่าน', value: '20 wheels Side Curtain' }]

interface region {
  label: string
  value: number
}
export const regionListEn: Array<region> = [
  { label: "north", value: 2 },
  { label: "north-east", value: 6 },
  { label: "south", value: 3 },
  { label: "west", value: 5 },
  { label: "center", value: 1 },
  { label: "east", value: 4 },
  { label: "all region", value: 7 },
]

export const regionListTh: Array<region> = [
  { label: "ภาคเหนือ", value: 2 },
  { label: "ภาคตะวันออกเฉียงเหนือ", value: 6 },
  { label: "ภาคใต้", value: 3 },
  { label: "ภาคตะวันตก", value: 5 },
  { label: "ภาคกลาง", value: 1 },
  { label: "ภาคตะวันออก", value: 4 },
  { label: "ทั่วประเทศ", value: 7 },
]

interface province {
  label: string
  value: number
  region: number
}

export const provinceListTh: Array<province> = [
  { "label": "กรุงเทพมหานคร", "value": 1, region: 1 },
  { "label": "สมุทรปราการ", "value": 57, region: 4 },
  { "label": "นนทบุรี", "value": 36, region: 1 },
  { "label": "ปทุมธานี", "value": 37, region: 1 },
  { "label": "พระนครศรีอยุธยา", "value": 46, region: 1 },
  { "label": "อ่างทอง", "value": 3, region: 1 },
  { "label": "ลพบุรี", "value": 22, region: 1 },
  { "label": "สิงห์บุรี", "value": 62, region: 1 },
  { "label": "ชัยนาท", "value": 7, region: 1 },
  { "label": "สระบุรี", "value": 60, region: 1 },
  { "label": "นครนายก", "value": 26, region: 1 },
  { "label": "ชลบุรี", "value": 12, region: 4 },
  { "label": "ระยอง", "value": 53, region: 4 },
  { "label": "จันทบุรี", "value": 9, region: 4 },
  { "label": "ตราด", "value": 71, region: 4 },
  { "label": "ฉะเชิงเทรา", "value": 6, region: 4 },
  { "label": "ปราจีนบุรี", "value": 49, region: 4 },
  { "label": "สระแก้ว", "value": 55, region: 4 },
  { "label": "นครราชสีมา", "value": 29, region: 6 },
  { "label": "บุรีรัมย์", "value": 5, region: 6 },
  { "label": "สุรินทร์", "value": 68, region: 6 },
  { "label": "ศรีสะเกษ", "value": 63, region: 6 },
  { "label": "อุบลราชธานี", "value": 72, region: 6 },
  { "label": "ยโสธร", "value": 77, region: 6 },
  { "label": "ชัยภูมิ", "value": 8, region: 6 },
  { "label": "อำนาจเจริญ", "value": 2, region: 6 },
  { "label": "บึงกาฬ", "value": 4, region: 6 },
  { "label": "หนองบัวลำภู", "value": 34, region: 6 },
  { "label": "ขอนแก่น", "value": 17, region: 6 },
  { "label": "อุดรธานี", "value": 73, region: 6 },
  { "label": "เลย", "value": 21, region: 6 },
  { "label": "หนองคาย", "value": 35, region: 6 },
  { "label": "มหาสารคาม", "value": 24, region: 6 },
  { "label": "ร้อยเอ็ด", "value": 54, region: 6 },
  { "label": "กาฬสินธุ์", "value": 14, region: 6 },
  { "label": "สกลนคร", "value": 56, region: 6 },
  { "label": "นครพนม", "value": 28, region: 6 },
  { "label": "มุกดาหาร", "value": 25, region: 6 },
  { "label": "เชียงใหม่", "value": 10, region: 2 },
  { "label": "ลำพูน", "value": 20, region: 2 },
  { "label": "ลำปาง", "value": 19, region: 2 },
  { "label": "อุตรดิตถ์", "value": 75, region: 2 },
  { "label": "แพร่", "value": 47, region: 2 },
  { "label": "น่าน", "value": 32, region: 2 },
  { "label": "พะเยา", "value": 41, region: 2 },
  { "label": "เชียงราย", "value": 11, region: 2 },
  { "label": "แม่ฮ่องสอน", "value": 23, region: 2 },
  { "label": "นครสวรรค์", "value": 30, region: 1 },
  { "label": "อุทัยธานี", "value": 74, region: 1 },
  { "label": "กำแพงเพชร", "value": 15, region: 1 },
  { "label": "ตาก", "value": 69, region: 5 },
  { "label": "สุโขทัย", "value": 65, region: 1 },
  { "label": "พิษณุโลก", "value": 45, region: 1 },
  { "label": "พิจิตร", "value": 44, region: 1 },
  { "label": "เพชรบูรณ์", "value": 42, region: 1 },
  { "label": "ราชบุรี", "value": 52, region: 5 },
  { "label": "กาญจนบุรี", "value": 16, region: 5 },
  { "label": "สุพรรณบุรี", "value": 66, region: 1 },
  { "label": "นครปฐม", "value": 27, region: 1 },
  { "label": "สมุทรสาคร", "value": 58, region: 1 },
  { "label": "สมุทรสงคราม", "value": 59, region: 1 },
  { "label": "เพชรบุรี", "value": 43, region: 5 },
  { "label": "ประจวบคีรีขันธ์", "value": 50, region: 5 },
  { "label": "นครศรีธรรมราช", "value": 31, region: 3 },
  { "label": "กระบี่", "value": 18, region: 3 },
  { "label": "พังงา", "value": 39, region: 3 },
  { "label": "ภูเก็ต", "value": 48, region: 3 },
  { "label": "สุราษฎร์ธานี", "value": 67, region: 3 },
  { "label": "ระนอง", "value": 51, region: 3 },
  { "label": "ชุมพร", "value": 13, region: 3 },
  { "label": "สงขลา", "value": 64, region: 3 },
  { "label": "สตูล", "value": 61, region: 3 },
  { "label": "ตรัง", "value": 70, region: 3 },
  { "label": "พัทลุง", "value": 40, region: 3 },
  { "label": "ปัตตานี", "value": 38, region: 3 },
  { "label": "ยะลา", "value": 76, region: 3 },
  { "label": "นราธิวาส", "value": 33, region: 3 },
]

export const provinceListEn: Array<province> = [
  { "label": "Bangkok", "value": 1, region: 1 },
  { "label": "Samut Prakarn", "value": 57, region: 4 },
  { "label": "Nonthaburi", "value": 36, region: 1 },
  { "label": "Pathum Thani", "value": 37, region: 1 },
  { "label": "Phra Nakhon Si Ayutthaya", "value": 46, region: 1 },
  { "label": "Ang Thong", "value": 3, region: 1 },
  { "label": "Lop Buri", "value": 22, region: 1 },
  { "label": "Sing Buri", "value": 62, region: 1 },
  { "label": "Chai Nat", "value": 7, region: 1 },
  { "label": "Saraburi", "value": 60, region: 1 },
  { "label": "Nakhon Nayok", "value": 26, region: 1 },
  { "label": "Chon Buri", "value": 12, region: 4 },
  { "label": "Rayong", "value": 53, region: 4 },
  { "label": "Chanthaburi", "value": 9, region: 4 },
  { "label": "Trat", "value": 71, region: 4 },
  { "label": "Chachoengsao", "value": 6, region: 4 },
  { "label": "Prachin Buri", "value": 49, region: 4 },
  { "label": "Sa kaeo", "value": 55, region: 4 },
  { "label": "Nakhon Ratchasima", "value": 29, region: 6 },
  { "label": "Buri Ram", "value": 5, region: 6 },
  { "label": "Surin", "value": 68, region: 6 },
  { "label": "Si Sa Ket", "value": 63, region: 6 },
  { "label": "Ubon Ratchathani", "value": 72, region: 6 },
  { "label": "Yasothon", "value": 77, region: 6 },
  { "label": "Chaiyaphum", "value": 8, region: 6 },
  { "label": "Amnat Charoen", "value": 2, region: 6 },
  { "label": "Bueng Kan", "value": 4, region: 6 },
  { "label": "Nong Bua Lam Phu", "value": 34, region: 6 },
  { "label": "Khon Kaen", "value": 17, region: 6 },
  { "label": "Udon Thani", "value": 73, region: 6 },
  { "label": "Loei", "value": 21, region: 6 },
  { "label": "Nong Khai", "value": 35, region: 6 },
  { "label": "Maha Sarakham", "value": 24, region: 6 },
  { "label": "Roi Et", "value": 54, region: 6 },
  { "label": "Kalasin", "value": 14, region: 6 },
  { "label": "Sakon Nakhon", "value": 56, region: 6 },
  { "label": "Nakhon Phanom", "value": 28, region: 6 },
  { "label": "Mukdahan", "value": 25, region: 6 },
  { "label": "Chiang Mai", "value": 10, region: 2 },
  { "label": "Lamphun", "value": 20, region: 2 },
  { "label": "Lampang", "value": 19, region: 2 },
  { "label": "Uttaradit", "value": 75, region: 2 },
  { "label": "Phrae", "value": 47, region: 2 },
  { "label": "Nan", "value": 32, region: 2 },
  { "label": "Phayao", "value": 41, region: 2 },
  { "label": "Chiang Rai", "value": 11, region: 2 },
  { "label": "Mae Hong Son", "value": 23, region: 2 },
  { "label": "Nakhon Sawan", "value": 30, region: 1 },
  { "label": "Uthai Thani", "value": 74, region: 1 },
  { "label": "Kamphaeng Phet", "value": 15, region: 1 },
  { "label": "Tak", "value": 69, region: 5 },
  { "label": "Sukhothai", "value": 65, region: 1 },
  { "label": "Phitsanulok", "value": 45, region: 1 },
  { "label": "Phichit", "value": 44, region: 1 },
  { "label": "Phetchabun", "value": 42, region: 1 },
  { "label": "Ratchaburi", "value": 52, region: 5 },
  { "label": "Kanchanaburi", "value": 16, region: 5 },
  { "label": "Suphan Buri", "value": 66, region: 1 },
  { "label": "Nakhon Pathom", "value": 27, region: 1 },
  { "label": "Samut Sakhon", "value": 58, region: 1 },
  { "label": "Samut Songkhram", "value": 59, region: 1 },
  { "label": "Phetchaburi", "value": 43, region: 5 },
  { "label": "Prachuap Khiri Khan", "value": 50, region: 5 },
  { "label": "Nakhon Si Thammarat", "value": 31, region: 3 },
  { "label": "Krabi", "value": 18, region: 3 },
  { "label": "Phang-nga", "value": 39, region: 3 },
  { "label": "Phuket", "value": 48, region: 3 },
  { "label": "Surat Thani", "value": 67, region: 3 },
  { "label": "Ranong", "value": 51, region: 3 },
  { "label": "Chumphon", "value": 13, region: 3 },
  { "label": "Songkhla", "value": 64, region: 3 },
  { "label": "Satun", "value": 61, region: 3 },
  { "label": "Trang", "value": 70, region: 3 },
  { "label": "Phatthalung", "value": 40, region: 3 },
  { "label": "Pattani", "value": 38, region: 3 },
  { "label": "Yala", "value": 76, region: 3 },
  { "label": "Narathiwat", "value": 33, region: 3 },
]
