export const vehicleEn: Array<Object> = [
    { label: 'Others', value: 'อื่นๆ' },
    { label: '4 Wheels - High Stall Truck', value: 'รถกระบะ 4 ล้อคอกสูง' },
    { label: '4 Wheels - Low Stall Truck', value: 'รถกระบะ 4 ล้อคอกเตี้ย' },
    { label: '4 Wheels - Flat Bed', value: 'รถกระบะ 4 ล้อพื้นเรียบ' },
    { label: '4 wheels - Cabinet Truck', value: 'รถกระบะ 4 ล้อตู้ทึบ' },
    { label: '4 wheels - Cabinet Truck + Temperature Controlled', value: 'รถกระบะห้องเย็น 4 ล้อตู้ทึบ' },
    { label: '4 Wheels - Cap Truck', value: 'รถกระบะ 4 ล้อหลังคาสูงทึบ' },
    { label: '4 wheels - Truck', value: 'รถกระบะ 4 ล้อ' },
    { label: '6 wheels - Stall Truck', value: 'รถ 6 ล้อตู้คอก' },
    { label: '6 wheels - Liquid Truck', value: 'รถบรรทุกของเหลว 6 ล้อ' },
    { label: '6 Wheels - Cabinet Truck', value: 'รถ 6 ล้อ ตู้ทึบ' },
    { label: '6 wheels - Flat Bed', value: 'รถ 6 ล้อพื้นเรียบ' },
    { label: '6 wheels - Pickup Truck', value: 'รถ 6 ล้อ กระบะ' },
    { label: '6 Wheels - Cabinet Truck - Temperature Controlled', value: 'รถห้องเย็น 6 ล้อตู้ทึบ' },
    { label: '6 Wheels - Crane', value: 'รถเครน 6 ล้อ' },
    { label: '10 Wheels - Crane', value: 'รถเครน 10 ล้อ' },
    { label: '10 Wheels - Stall + Dump Truck', value: 'รถ 10 ล้อคอกดัมพ์' },
    { label: '10 Wheels - Chemical Tanker', value: 'รถ 10 ล้อ เคมีภัณฑ์' },
    { label: '10 Wheels - Stall Truck', value: 'รถ 10 ล้อคอก' },
    { label: '10 Wheels - Cabinet Truck', value: 'รถ 10 ล้อ ตู้ทึบ' },
    { label: '10 Wheels - Flat Bed', value: 'รถ 10 ล้อ พื้นเรียบ' },
    { label: '10 Wheels - Liquid Tanker', value: 'รถ 10 ล้อบรรทุกของเหลว' },
    { label: '10 Wheels - Cabinet Truck - Temperature Controlled', value: 'รถห้องเย็น 10 ล้อตู้ทึบ' },
    { label: '10 wheels - Fuel Tanker', value: 'รถ 10 ล้อ บรรทุกน้ำมัน' },
    { label: '18 Wheels - Flat Bed', value: 'รถหัวลาก 18 ล้อ พื้นเรียบ' },
    { label: 'Semi - Trailer Cement Tanker', value: 'รถบรรทุกปูนซีเมนต์ประเภทผง' },
    { label: '40” Trailer - Cabinet Truck', value: 'รถหัวลาก 18 ล้อ ตู้ทึบ 40 ฟุต' },
    { label: '40” Trailer - Cabinet Truck - Temperature Controlled', value: 'รถเทรเลอร์คอนเทรนเนอร์ ห้องเย็น 40 ฟุต' },
    { label: '40” Trailer 18 Wheels - Stall Truck', value: 'รถพ่วงคอก 40 ฟุต' },
    { label: '20” Trailer 18 Wheels - Stall Truck + Dump', value: 'รถพ่วงคอกดัมพ์' },
    { label: '40” Trailer 18 Wheels - Stall Truck + Dump', value: 'รถพ่วงดัมพ์ 40 ฟุต' },
    { label: '18 Wheels - Skeleton Semi Trailer', value: 'เทรลเลอร์ก้างปลา' },
    { label: 'Tractor Head Truck', value: 'รถหัวลาก' },
    { label: 'Car Carrier Trailer', value: 'รถบรรทุกรถ' },
    { label: 'Bike Carrier Truck', value: 'รถบรรทุกจักรยานยนต์' },
    { label: '20” Trailer, 18 Wheels - Cabinet Truck', value: 'รถพ่วง 18 ล้อตู้ทึบ 20 ฟุต' },
    { label: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', value: 'รถพ่วงตู้ทึบ 20 ฟุต' },
    { label: '20” Trailer 18 Wheels - Stall Truck', value: 'รถพ่วงคอก 20 ฟุต' },
    { label: 'Trailer 22 wheels Side Curtain', value: 'รถเทรเลอร์เปิดข้างผ้าม่าน' },
    { label: '20 wheels Side Curtain', value: 'รถพ่วงเปิดข้างผ้าม่าน' },]


export const vehicleTh: Array<Object> = [
    { label: 'อื่นๆ', value: 'Others', },
    { label: 'รถกระบะ 4 ล้อคอกสูง', value: '4 Wheels - High Stall Truck', },
    { label: 'รถกระบะ 4 ล้อคอกเตี้ย', value: '4 Wheels - Low Stall Truck', },
    { label: 'รถกระบะ 4 ล้อพื้นเรียบ', value: '4 Wheels - Flat Bed', },
    { label: 'รถกระบะ 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck', },
    { label: 'รถกระบะห้องเย็น 4 ล้อตู้ทึบ', value: '4 wheels - Cabinet Truck + Temperature Controlled', },
    { label: 'รถกระบะ 4 ล้อหลังคาสูงทึบ', value: '4 Wheels - Cap Truck', },
    { label: 'รถกระบะ 4 ล้อ', value: '4 wheels - Truck', },
    { label: 'รถ 6 ล้อตู้คอก', value: '6 wheels - Stall Truck', },
    { label: 'รถบรรทุกของเหลว 6 ล้อ', value: '6 wheels - Liquid Truck', },
    { label: 'รถ 6 ล้อ ตู้ทึบ', value: '6 Wheels - Cabinet Truck', },
    { label: 'รถ 6 ล้อพื้นเรียบ', value: '6 wheels - Flat Bed', },
    { label: 'รถ 6 ล้อ กระบะ', value: '6 wheels - Pickup Truck', },
    { label: 'รถห้องเย็น 6 ล้อตู้ทึบ', value: '6 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถเครน 6 ล้อ', value: '6 Wheels - Crane', },
    { label: 'รถเครน 10 ล้อ', value: '10 Wheels - Crane', },
    { label: 'รถ 10 ล้อคอกดัมพ์', value: '10 Wheels - Stall + Dump Truck', },
    { label: 'รถ 10 ล้อ เคมีภัณฑ์', value: '10 Wheels - Chemical Tanker', },
    { label: 'รถ 10 ล้อคอก', value: '10 Wheels - Stall Truck', },
    { label: 'รถ 10 ล้อ ตู้ทึบ', value: '10 Wheels - Cabinet Truck', },
    { label: 'รถ 10 ล้อ พื้นเรียบ', value: '10 Wheels - Flat Bed', },
    { label: 'รถ 10 ล้อบรรทุกของเหลว', value: '10 Wheels - Liquid Tanker', },
    { label: 'รถห้องเย็น 10 ล้อตู้ทึบ', value: '10 Wheels - Cabinet Truck - Temperature Controlled', },
    { label: 'รถ 10 ล้อ บรรทุกน้ำมัน', value: '10 wheels - Fuel Tanker', },
    { label: 'รถหัวลาก 18 ล้อ พื้นเรียบ', value: '18 Wheels - Flat Bed', },
    { label: 'รถบรรทุกปูนซีเมนต์ประเภทผง', value: 'Semi - Trailer Cement Tanker', },
    { label: 'รถหัวลาก 18 ล้อ ตู้ทึบ 40 ฟุต', value: '40” Trailer - Cabinet Truck', },
    { label: 'รถเทรเลอร์คอนเทรนเนอร์ ห้องเย็น 40 ฟุต', value: '40” Trailer - Cabinet Truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถพ่วงคอกดัมพ์', value: '20” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'รถพ่วงดัมพ์ 40 ฟุต', value: '40” Trailer 18 Wheels - Stall Truck + Dump', },
    { label: 'เทรลเลอร์ก้างปลา', value: '18 Wheels - Skeleton Semi Trailer', },
    { label: 'รถหัวลาก', value: 'Tractor Head Truck', },
    { label: 'รถบรรทุกรถ', value: 'Car Carrier Trailer', },
    { label: 'รถบรรทุกจักรยานยนต์', value: 'Bike Carrier Truck', },
    { label: 'รถพ่วง 18 ล้อตู้ทึบ 20 ฟุต', value: '20” Trailer, 18 Wheels - Cabinet Truck', },
    { label: 'รถพ่วงตู้ทึบ 20 ฟุต', value: '20” Trailer 18 Wheels - Cabinet truck - Temperature Controlled', },
    { label: 'รถพ่วงคอก 20 ฟุต', value: '20” Trailer 18 Wheels - Stall Truck', },
    { label: 'รถเทรเลอร์เปิดข้างผ้าม่าน', value: 'Trailer 22 wheels Side Curtain', },
    { label: 'รถพ่วงเปิดข้างผ้าม่าน', value: '20 wheels Side Curtain' }]